### ISSUE TITLE
Please make a plain text version available

### ISSUE THREAD

**Issue by gregdek** [opensourceway/open-decision-framework#3]
If the intention is to allow users to fork and/or patch, the binary odp format is contrary to that intention. Makes it impossible to see changes between different versions, make pull requests, etc.

**Comment by jehb** [comment]
@gregdek @berecka I think I could pretty easily convert the ODP to a Markdown or RST file and add it to the repo -- which format do you think makes the most sense? Either? Both? Something else?

**Comment by gregdek** [comment]
@jehb markdown is probably easiest if you want contribution back, since people can then edit directly in the GitHub editor.

**Comment by berecka** [comment]
That works for me. Does it make sense to maintain an odp and PDF for those who want to download and use it but aren't familiar with markdown?

**Comment by berecka** [comment]
@gregdek I've maintained a plain text log of changes since 2014 for the internal Red Hat version but it is definitely cumbersome. Open to trying markdown or other alternatives.

**Comment by gregdek** [comment]
This is the problem with Github as a repository for pretty things. :/

It would be straightforward to create a master copy in Markdown and then use something like https://github.com/thorstenb/odpdown every time you "release" to create the ODP version, but it's very likely that you'd lose the nice formatting. 

If markdown is too cumbersome, plain text would be something.

**Comment by berecka** [comment]
@jehb If you have time, see if the markdown conversion is feasible. If not, let me know and I can add a plain text one. 

I wonder if recreating the deck in slides.com would work, because then it could be downloaded as folder of HTML/CSS files (where changes should be easily tracked, no?) or exported as a PDF...

**Comment by jehb** [comment]
@berecka I'm working on a Markdown version, probably won't finish with it tonight but I'll ping you tomorrow to let you have a look before I push it into the repo. It's almost identical text, but there are a few places where I remove the CAPS to make it easier to read in this format, and it may make sense to add a few "helper words" to make it clear that Principles (lead to) Practices (lead to) Outcomes when the visual arrows are removed.

**Comment by lintqueen** [comment]
Aren't there now some tools that let you house the backend content in
GitHub and make it "pretty" via a web front end?  I think many of our
community sites now work that way (but I don't know the specific technology
involved... the OSAS team would).

If we're not wedded to it being a "deck" and instead started thinking of it
as content that needs a navigational framework, that might be a possible
solution.

-gina

On Wed, Jun 1, 2016 at 9:11 PM, Greg DeKoenigsberg <notifications@github.com
> wrote:

> If the intention is to allow users to fork, the binary odp format is
> contrary to that intention. Makes it impossible to see changes between
> different versions, make pull requests, etc.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/opensourceway/open-decision-framework/issues/3>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGeuuQVERbR6ndBRJXelVZesSZ2Xn89vks5qHi3bgaJpZM4IsHqg>
> .
>



-- 
~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
My brain seems to have a circuit-breaker-like mechanism that, when I get
confused and befuddled by the overwhelming monstrosities of my life, causes
a default to the simplest and most pleasant of thoughts. Like Marshmallow
Peeps. I *like* Marshmallow Peeps.
Gina Likins
gina@lintqueen.com (me personally)                               @lintqueen
on Twitter
http://www.lintqueen.com
~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*

**Comment by berecka** [comment]
@lintqueen Can you share an example? Can't quite picture what you're describing.

**Comment by lintqueen** [comment]
Yes - meetings all day today but will try to find a break. :-)

Gina 

Pardon my thumb-clumsiness.

**Comment by jehb** [comment]
Markdown will (theoretically) drop nicely into Reveal.js, which is the same backend as slides.redhat.com. Maybe step 2 after getting a passable markdown version would be pairing it with a nice Reveal.js template, and therefore the same "code" could be both human-editable on GitHub and easy to present with.

**Comment by gregdek** [comment]
Big +1 to using reveal.js.

**Comment by lintqueen** [comment]
Okay - I asked our people and here's what they said:

(09:40:47 AM) The topic for #osas is: Open Source and Standards | https://mojo.redhat.com/docs/DOC-1059471
(09:40:47 AM) Topic for #osas set by amye!~ascavard@10.3.11.40 at 01:05:16 AM on 05/12/2016
(09:40:56 AM) mguerett left the room (quit: Ping timeout: 624 seconds).
(09:42:05 AM) Duck: glikins: you mean statically generated websites?
(09:42:42 AM) dblack|ENOENT is now known as dblack
(09:47:37 AM) moshe|wfh|afk_gone is now known as moshe
(09:49:01 AM) moshe is now known as moshe|wfh
(09:53:13 AM) glikins: Duck: yes? (I think) 
(09:54:20 AM) msivanes is now known as msivanes|afk
(09:55:03 AM) Duck: glikins2: so I'm aware of a few sites using MiddleMan to generate a static site and maintained by OSAS Infra team
(09:55:30 AM) glikins: cool -- who?
(09:55:57 AM) Duck: glikins2: community.redhat.com, www.ovirt.org, rdoproject.org, manageiq.org, gluster.org, projectatomic.io
(09:56:09 AM) Duck: glikins2: Misc and me
(09:56:26 AM) rmc [~rmc@vpn1-6-13.sin2.redhat.com] entered the room.
(09:56:48 AM) rmc is now known as rmc|mtg
(09:57:09 AM) glikins: cool!  do you have a how doc?
(09:57:11 AM) drieden is now known as drieden_mtg
(09:57:14 AM) glikins: (how does it work)
(09:57:16 AM) Duck: glikins2: there is for each a builder VM either on OS1 or OpenShift to fetch the git pushes, build, and push the content to production
(09:57:48 AM) Duck: I have notes from Misc and there is basic doc in each repo

**Comment by gregdek** [comment]
@lintqueen I suspect this is far more complicated than you want/need -- unless you plan to maintain this as a web site. A simple conversion from markdown to reveal.js and putting the result on slides.redhat.com is the way to go, I think.

**Comment by lintqueen** [comment]
That's probably true, Greg... I think it is more complicated than needed... Unless it wants to be a website long-term.
