### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by grivalta** [opensourceway/open-decision-framework#31]
Hi to all,

I've started a translation of ODF in italian language: a WIP of the translated MD file is in my [repo](https://github.com/grivalta/open-decision-framework/tree/master/it_IT), forked from yours. First of all, do you know if there are other work in progress to do this, to eventually integrate mine?
I'm not a great english speaker, but I hope my little contribute can help some italian user to know and understand the ODF... With the objective of increment, complete and perfectionating the translation I hope also to see asap some other italian speaker's committers working on it :)

At the moment, due to the current state of localisation, I considered it unnecessary to delete the references to Red Hat. But if you think it is necessary then I will make the correction, perhaps inserting a reference to a generic company. Some fundamental clarifications about the choices made regarding the terminology and its localization in Italian would be necessary. As well as the decision not to translate some terms but leaving them in English, because they have entered the common use in our language.

I want to give many thanks to @daamien  and other french contributors, because their previous work helped me very well to address mine. Many thanks obiously to Red Hat and you all for the great ODF project!

Next I write some motivational consideration about my interest in ODF and other open source similar works.
Best regards. gianluca

**Comment by ruhbehka** [comment]
Hi gianluca, 
Very exciting, thank you for doing our first Italian translation! I shall share your fork with some colleagues in Italy, and see if they would submit any suggested edits or enhancements, so you will feel more confident that the translation is a good one. :) 

When you are happy with it, please submit a pull request, and I will figure out how to add it to the main repo. I shall have to review what I did for @daamien 's French version, and repeat those steps to create our Italian version.

I agree, keep it a 1:1 translation with references to Red Hatters, then people can fork it and make their own adaptations to fit their organization's name or culture. People will feel more sure they have the "official" version if the wording mirrors the English, I think.

I will leave it to future Italian collaborators to debate whether words should be translated in an approximate Italian form or left in English, as that feels like a decision that would require better grasp of English than I have.

Thank you!

**Comment by daamien** [comment]
Hello

Thanks for the mention ! Unfortunatelly I don't speak italian but let me know if I can help you with this translation process.

**Comment by bonzini** [comment]
Thanks Gianluca! I did a little copy editing on your markdown file and created a pull request at https://github.com/grivalta/open-decision-framework/pull/1.

**Comment by bonzini** [comment]
I created another pull request with Antonella's edits. She did a great job improving the prose!

I'm not sure about the translation of "Lead with transparency", which could be rendered as:
* "Guidate in trasparenza" (most literal translation, but sounds ugly)
* "Agite con trasparenza" ("act with transparency")
* "Siate leader trasparenti" ("be transparent leaders")
* "Mostrate la via nella transparenza" ("show the way with transparency")

Neither is perfect I'm afraid, and I am not sure which one matches best the intent of the original document.

**Comment by grivalta** [comment]
Thank to you and Antonella Iecle. In these days I try to review your PR. My firt comments are in PR conversation tab.

**Comment by ruhbehka** [comment]
> I created another pull request with Antonella's edits. She did a great job improving the prose!
> 
> I'm not sure about the translation of "Lead with transparency", which could be rendered as:
> 
>     * "Guidate in trasparenza" (most literal translation, but sounds ugly)
> 
>     * "Agite con trasparenza" ("act with transparency")
> 
>     * "Siate leader trasparenti" ("be transparent leaders")
> 
>     * "Mostrate la via nella transparenza" ("show the way with transparency")
> 
> 
> Neither is perfect I'm afraid, and I am not sure which one matches best the intent of the original document.

@bonzini In this case, the meaning of "lead" is more like "begin" but it's a bit of a play on words, as it also carries a secondary meaning of "be a leader". It's meant to imply something like: "start the process in the same way that you hope to finish it: by being transparent. Don't wait until you're nearly finished to start sharing information. Lead the project or decisions transparently, from the very beginning."

Of your four options, "Mostrate la via nella transparenza" ("show the way with transparency") seems closest, or perhaps you and Antonella may think of a better way to capture that. If it's too nuanced to translate well, I would probably take a more literal wording like "begin your work by being transparent".

**Comment by ruhbehka** [comment]
@bonzini @grivalta Can you let me know when you are happy with the translation, and I'll figure out how to add it into the official repo, like we did with the French version.

**Comment by grivalta** [comment]
Hi to all,
in January I merged with squash the [Pull Req.](https://github.com/grivalta/open-decision-framework/pull/2) of @bonzini  but some problem has broken the file, so [I had to revert at the previous state](https://github.com/grivalta/open-decision-framework/pull/3).
Then throughout this quarter I have been busy with other projects, so sorry for the late in correcting the situation...

Recently I re-executed all the commits (of that PR) step by step to identify the one that introduced the indicated error and to preserve the entire history of the contributions of their authors.
Now I think the file is fine, especially thanks to the remarkable work done by Antonella Iecle and Bonzini  :)

Regarding the discussion ([issuecomment-451986724](https://github.com/red-hat-people-team/open-decision-framework/issues/31#issuecomment-451986724)), I thought of leaving the original "Agite con trasparenza" ("act with transparency") because it seems to me sufficiently suitable. What do you think about?

As a matter of curiosity: the problem that led to the revert of last PR, was connected to an Html comment not closed just on this topic ([my commmit](https://github.com/grivalta/open-decision-framework/commit/1b0e925dd21f6740cd299958dd9e0d968cb4f440)).

For now, in my opinion, the translation could be released. What is better to do now?
Thanks.

**Comment by ruhbehka** [comment]
This is very excellent, thank you all for your efforts! 

Here's the new directory for the Italian translation: https://github.com/red-hat-people-team/open-decision-framework/tree/master/it_IT 

1. I have created a template called TRANSLATION.md that should be filled out, with any relevant details you would like future contributors or users to know, e.g. "We translated "Lead with transparency" as "Act with transparency" because..."

2. Please submit your Italian ODF-community.MD file to the same folder as a pull request, and we'll see if that works. If not, I can copy and paste the MD file contents, but I'd prefer to keep the traceability between your original creation and the subsequent addition into the repo!

3. I will see if Antonella can use the MD file contents to create the .ODP and .PDF versions of the files. If not, I'll try to do it myself, but someone who speaks Italian should look closely at my copying and pasting! :)

**Comment by ruhbehka** [comment]
Update: @bonzini got us started with the Translation.MD file, and Antonella has agreed to complete it by the end of March. 

Items still outstanding:

- @grivalta Please submit your Italian ODF-community.MD file to the same folder as a pull request, and we'll see if that works. If not, I can copy and paste the MD file contents, but I'd prefer to keep the traceability between your original creation and the subsequent addition into the repo!

- Someone needs to copy and paste the MD file contents into the .ODF version of the files, and then export to .PDF. It's best if this is done by an Italian speaker, so I have asked Antonella and @bonzini if one of them can complete this. If not, I'll try to do it myself, but someone who speaks Italian should look closely at my copying and pasting! :)

**Comment by grivalta** [comment]
Ok, many thanks for this roadmap. I have just submitted the pull request, hoping to have done everything right.
Waiting for your feedback, thanks...

**Comment by ruhbehka** [comment]
Excellent, I have merged it. Thank you!
