### ISSUE TITLE
Strip internal URLs from links

### ISSUE THREAD

**Issue by jehb** [opensourceway/open-decision-framework#4]
While working on a Markdown version for #3, I discovered that two of the URLs on slide 12 (Resources) are structured in such a way as to include the URL for Red Hat's internal wiki with a redirect. No security risk or anything, but they won't work for someone who's not able to log in to that site (although someone could probably figure out what the link was *supposed* to be from the embedded link).

**Comment by berecka** [comment]
Weird. I'll fix. Thanks.
